### ISSUE TITLE
Cockpit

### ISSUE THREAD

**Issue by saltydk** [saltyorg/Saltbox#142]
Add https://cockpit-project.org to Saltbox if it won't cause any conflicts.

**Comment by m1lkman** [comment]
@saltydk I'd like to mess around with this. Do you have any working docker-compose examples for cockpit?

**Comment by saltydk** [comment]
I was installing it on the host in our initial tests months ago. These are the notes that came from that, very loose as it was not tested well.

```shell
sudo apt install -t focal-backports cockpit cockpit-machines
sudo apt install qemu qemu-kvm libvirt-clients libvirt-daemon-system virtinst bridge-utils
sudo apt-get install cracklib-runtime
sudo apt-get install qemu-utils
sudo apt-get install dnsmasq
sudo virsh net-start default
```




/etc/cockpit/cockpit.conf
```ini
[WebService]
Origins = https://cockpit.dev.saltbox.dev
ProtocolHeader = X-Forwarded-Proto
ForwardedForHeader = X-Forwarded-For
AllowUnencrypted = true
```

"/etc/systemd/system/cockpit.socket.d/listen.conf"
```ini
[Socket]
ListenStream=
ListenStream=172.19.0.1:1337
FreeBind=yes
```


traefik
```yaml
http:
  services:
    cockpit:
      loadBalancer:
        servers:
          - url: "http://172.19.0.1:1337/"
  routers:
    cockpit:
      entryPoints:
        - "websecure"
      rule: "Host(`cockpit.dev.saltbox.dev`)"
      middlewares:
        - "secureHeaders@file,gzip@docker"
      tls:
        certresolver: "zerossl"
        options: "securetls@file"
      service: "cockpit"
```

**Comment by saltydk** [comment]
The above is from testing on focal so obviously need some tweaks for jammy.

**Comment by RaneyDazed** [comment]
I have it running, not sure if its set up how salty would do it. 

```bash
sudo apt install -t jammy-backports cockpit
```

`/etc/cockpit/cockpit.conf`

```ini
[WebService]
Origins = https://cockpit.domain.tld
ProtocolHeader = X-Forwarded-Proto
ForwardedForHeader = X-Forwarded-For
AllowUnencrypted = true
```

`/etc/systemd/system/cockpit.socket.d/listen.conf`

```ini
[Socket]
ListenStream=
ListenStream=172.19.0.1:1337
FreeBind=yes
```

traefik `/opt/traefik/cockpit.yml`

```yaml
http:
  services:
    cockpit:
      loadBalancer:
        servers:
          - url: "http://172.19.0.1:1337/"
  routers:
    cockpit:
      entryPoints:
        - "websecure"
      rule: "Host(`cockpit.domain.tld`)"
      middlewares:
        - "globalHeaders@file"
      tls:
        certresolver: "cfdns"
        options: "securetls@file"
      service: "cockpit"
      ```
![image](https://github.com/saltyorg/Saltbox/assets/95461636/69ffda54-240a-47b9-842d-b8e43b0ccc2b)
idk if the image will show. but it loads fine. logged in and everything seems to look alright. I tried some of the other middlewares but I'm stupid so they didn't work.
