### ISSUE TITLE
Settings: rewrite

### ISSUE THREAD

**Issue by saltydk** [saltyorg/Saltbox#154]
Clean up the settings role to use dynamic include_tasks instead of the current implementation that is fairly spammy and confusing to debug.

Current implementation:
```yaml
- name: "Settings | Migrator"
  ansible.builtin.include_tasks: "subtasks/migrator.yml"
  vars:
    file: "{{ outer_item }}"
 ```
 
 Initial suggestion would be:
```yaml
- name: "Settings | Migrator"
  ansible.builtin.include_tasks: "subtasks/migrator/{{ outer_item }}.yml"
```

This would avoid looping over tasks that aren't going to do anything over and over.
