### ISSUE TITLE
Plex: add more convinient lan custom url to the local port binding toggle

### ISSUE THREAD

**Issue by saltydk** [saltyorg/Saltbox#155]
Currently
```yaml
plex_open_main_ports: true
plex_open_local_ports: true
plex_docker_envs_advertise_ip: "http://LANIP:32400,{{ lookup('vars', plex_name + '_docker_envs_advertise_ip_url', default=plex_docker_envs_advertise_ip_url) }}"
```
Ideally we'd just want something like
```yaml
plex_open_main_ports: true
plex_open_local_ports: true
plex_lan_ip: "LANIP"
```
to override the LAN IP we could attempt an automatic lookup for.
