### ISSUE TITLE
remotes: add upload toggle to settings.yml

### ISSUE THREAD

**Issue by saltydk** [saltyorg/Saltbox#159]
Chaz had a suggestion to change the current traefik3 layout of
```yaml
rclone:
  enabled: true
  remotes:
    - remote: google
      template: google
      vfs_cache:
        enabled: false
        max_age: 504h
        size: 50G
  version: latest
 ```
 to something like
 ```yaml
 rclone:
  enabled: true
  remotes:
    - remote: google
      template: google
      upload: true
      upload_from: /mnt/local/Media
      vfs_cache:
        enabled: false
        max_age: 504h
        size: 50G
  version: latest 
 ```
 Which would allow a way to generate a cloudplow config that is setup to use multiple remotes to upload from different source folders with fairly little work from the user.
 
 Additionally this would allow us to decouple the use of cloudplow from the Mediabox/Feederbox tags and let users decide if they want to use cloudplow or not through the config and what folders they want to upload more importantly.
 
 Add a cloudplow-reset style tag to redo the entire config generation.
