### ISSUE TITLE
Add mount and mergerfs toggle to remotes

### ISSUE THREAD

**Issue by saltydk** [saltyorg/Saltbox#170]
The current format of
```yaml
rclone:
  enabled: true
  remotes:
    - remote: google
      template: google
      upload: true
      upload_from: /mnt/local/Media
      vfs_cache:
        enabled: false
        max_age: 504h
        size: 50G
  version: latest
  ```
  Has a limitation in scenarios where the user adds upload remotes that aren't supposed to be mounted or if they want to mount something but avoid adding it to the mergerfs union.
  
```yaml
rclone:
  enabled: true
  remotes:
    - remote: google
      template: google
      unionfs: true
      upload: true
      upload_from: /mnt/local/Media
      upload_only: false
      vfs_cache:
        enabled: false
        max_age: 504h
        size: 50G
  version: latest
```
Is one suggestion as to how it could look but if anyone has a better idea feel free to comment. Just be aware that we sort the keys alphabetically these days so that sort of limits my first thought of adding mount: true as one of the keys as it would look weird not to have the name of the remote at the top.

The example from above would be something like

```yaml
rclone:
  enabled: true
  remotes:
    - mount: true
      remote: google
      template: google
      unionfs: true
      upload: true
      upload_from: /mnt/local/Media
      vfs_cache:
        enabled: false
        max_age: 504h
        size: 50G
  version: latest
```
