### ISSUE TITLE
Lock down ansible.cfg from user edits.

### ISSUE THREAD

**Issue by saltydk** [saltyorg/Saltbox#22]
A replacement for skip_tags will have to be implemented in the sb tool https://github.com/saltyorg/sb/issues/2

**Comment by saltydk** [comment]
One idea for custom tags. Load list from a config and run:
```yaml
- name: Use role in loop
  include_role:
    name: "{{ role_list_item }}"
  with_items:
    - 'sonarr'
    - 'radarr'
  loop_control:
    loop_var: role_list_item
    ```
