### ISSUE TITLE
Download location settings.

### ISSUE THREAD

**Issue by saltydk** [saltyorg/Saltbox#24]
We should rework the current download path setup currently used as it interferes with roles that want a generic download folder not related to nzb or torrents.

Current suggestion is to change settings.yml option to:
``` yaml
downloads: /mnt/local/downloads
```
And build the remaining nzb/torrent sub-paths through the inventory system to allow for override capability should the user still need it.

Alternately we could do the following:
``` yaml
downloads:
  generic: /mnt/local/downloads
  nzbs: /mnt/local/downloads/nzbs
  torrents: /mnt/local/downloads/torrents
```
