### ISSUE TITLE
Multiple remotes

### ISSUE THREAD

**Issue by saltydk** [saltyorg/Saltbox#26]
Tweak settings.yml remote variable to either be a list or provide some other way of mounting multiple mounts. Either defaulting to a union or creating a dictionary so you select the mount profiles per remote.

**Comment by saltydk** [comment]
Suggested config format
```yaml
rclone:
  version: latest
  remotes:
    - remote: google
      type: google
      cache: false
      port: 5572
    - remote: dropbox
      type: dropbox
      cache: false
      port: 5573
    - remote: feeder
      type: sftp
      cache: false
      port: 5574
 ```

**Comment by saltydk** [comment]
Prompt for remote type when migrating the config instead of relying on a lookup that could break down the line 
```yaml
- name: Prompt for something
  ansible.builtin.pause:
    prompt: "Enter something"
    echo: true
  register: pause_prompt

- name: Set something
  ansible.builtin.set_fact:
    something: "{{ pause_prompt.user_input }}"

- name: Debug
  ansible.builtin.debug:
    var: something
```

**Comment by saltydk** [comment]
Template ended up being
```yaml
rclone:
  version: latest
  remotes:
    - remote: google
      template: google
      cache:
        enabled: false
        size: 50G
        max_age: 504h
      port: 5572
```
Migration will just assume google template for now as that is the simplest solution.

New folder layout will ditch /mnt/feeder and place the remote(s) in /mnt/remote/<name of remote> and mergerfs branches will be added dynamically, hence me questioning if we should keep mounts_override. 

This change of layout is likely a non-trivial change that may require some manual intervention for people with feeder mounts currently or other complex setups that may benefit from migrating to this new way of dealing with multiple remotes without using union.

TODO:
* Decide if we should delete or keep a backup of the old rclone_vfs.service seeing as the new format doesn't use that service name anymore.
* Should we keep the current mounts_override logic now that we can load templates that do whatever people want.
* Should we add automated migration for feeder? Given the possibility of port conflicts with the new layout I am leaning towards this being a docs issue instead.

If anyone has any suggestions now would be the time before we lock in the new format.

**Comment by saltydk** [comment]
Disabling remote logic will be done like so:
```yaml
rclone:
  version: latest
  remotes: []
```
