### ISSUE TITLE
Arrs Instance Name Update

### ISSUE THREAD

**Issue by Barrow1990** [saltyorg/Saltbox#317]
---

**Describe the problem**
Having being messing with the API I noticed there's a endpoint at sonarr:8989/initialize.json which outputs the following:
```json
{
  "apiRoot": "/api/v3",
  "apiKey": "APIKEY",
  "release": "4.0.13.2932-main",
  "version": "4.0.13.2932",
  "instanceName": "Sonarr",
  "theme": "auto",
  "branch": "main",
  "analytics": true,
  "userHash": "userHASH",
  "urlBase": "",
  "isProduction": true
}
```

the config file also outputs it:
```xml
<Config>
  <BindAddress>*</BindAddress>
  <Port>8989</Port>
  <SslPort>9898</SslPort>
  <EnableSsl>False</EnableSsl>
  <LaunchBrowser>True</LaunchBrowser>
  <ApiKey>APIKEY</ApiKey>
  <AuthenticationMethod>External</AuthenticationMethod>
  <AuthenticationRequired>Enabled</AuthenticationRequired>
  <Branch>main</Branch>
  <LogLevel>debug</LogLevel>
  <SslCertPath />
  <SslCertPassword />
  <UrlBase />
  <InstanceName>Sonarr</InstanceName>
  <UpdateMechanism>Docker</UpdateMechanism>
</Config>%
```

With the fact that multiple instances are available within the saltbox ecosystem.
I feel the instanceName should reflect the instance name that you have derived in the arrs_instances variable.

**Describe any solutions you think might work**
The config file requires updating to reflect this change

**Additional context**
I've had a play around and would seem that updating the config file doesn't update the item.
This may require to update via api.

attempt of the yaml file:
```yaml
#########################################################################
# Title:         Saltbox: Sonarr | InstanceName Tasks                   #
# Author(s):     Barrow1990                                             #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: InstanceName | Wait for 'config.xml' to be created
  ansible.builtin.wait_for:
    path: "/opt/{{ sonarr_name }}/config.xml"
    state: present

- name: InstanceName | Wait for 10 seconds
  ansible.builtin.wait_for:
    timeout: 10

- name: InstanceName | Lookup InstanceName value
  community.general.xml:
    path: "/opt/{{ sonarr_name }}/config.xml"
    xpath: "/Config/InstanceName"
    content: "text"
  register: xmlresp

- set_fact:
    instance_name: "{{ xmlresp.matches[0].InstanceName }}"

- block:
    - name: InstanceName | Change the 'InstanceName' attribute to '{{ sonarr_name }}'
      when: instance_name is defined and instance_name != sonarr_name
      community.general.xml:
        path: "/opt/{{ sonarr_name }}/config.xml"
        xpath: "/Config/InstanceName"
        value: "{{ sonarr_name }}"

    - name: InstanceName| Restart Docker container
      ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/restart_docker_container.yml"
```
