### ISSUE TITLE
Refactor instances

### ISSUE THREAD

**Issue by saltydk** [saltyorg/Saltbox#331]
Move instance based lookups into the create_docker_container resource to simplify roles to some extent and create less maintenance in roles themselves as we expose features in the future. This would allow inventory edits of renamed deployments as well in roles that aren't setup to use instancing yet.

**Comment by saltydk** [comment]
This could be an opportunity to decouple the default instance from any additional ones, the issue being that if you want to edit the main instance, currently, without affecting the additional instances you would be required to modify all of them.

**Comment by saltydk** [comment]
Role change could look like this:
```yaml
# Image
plex_role_docker_image_pull: true
plex_role_docker_image_repo: "plexinc/pms-docker"
plex_role_docker_image_tag: "latest"
plex_role_docker_image: "{{ lookup('vars', plex_name + '_docker_image_repo', default=plex_role_docker_image_repo)
                            + ':' + lookup('vars', plex_name + '_docker_image_tag', default=plex_role_docker_image_tag) }}"
```
Where changing plex_role_docker_image_repo changes things for all instances but plex_docker_image_repo only changes it for the instance named plex.

For non-instanced roles we'd do stuff like:
```yaml
- name: Resources | Tasks | Docker | Create Docker Container | Set '_var_prefix' variable
  ansible.builtin.set_fact:
    _var_prefix: "{{ var_prefix
                  if (var_prefix is defined)
                  else role_name }}"

- name: Resources | Tasks | Docker | Create Docker Container | Set instance name
  ansible.builtin.set_fact:
    _instance_name: "{{ lookup('vars', _var_prefix + '_name', default=_var_prefix) }}"

- name: Resources | Tasks | Docker | Create Docker Container | Network Container Health Status
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/network_container_health_status.yml"
  when: ('container:' in lookup('vars', _instance_name + '_docker_network_mode', default=lookup('vars', _var_prefix + '_role_docker_network_mode', default=docker_networks_name_common)))

- name: Resources | Tasks | Docker | Create Docker Container | Create Docker Container # noqa args[module]
  community.docker.docker_container:
    auto_remove: "{{ lookup('vars', _instance_name + '_docker_auto_remove', default=lookup('vars', _var_prefix + '_role_docker_auto_remove', default=omit)) }}"
...
```
Where it tries the variables not defined by the role first, if you changed the name variable, eg dozzle_name, and otherwise does the same lookup as normally. This will be slower but more flexible.
