### ISSUE TITLE
Change nomenclature in backup config

### ISSUE THREAD

**Issue by chazlarson** [saltyorg/Saltbox#34]
```
  cron:
    cron_time: weekly
    cron_state: absent/present
```
That "absent/present" thing is really non-intuitive.  I'd suggest changing it to something like:
```
  cron:
    cron_time: weekly
    schedule_with_cron: yes/no
```

**Comment by saltydk** [comment]
```yaml
cron:
  cron_time: weekly
  enable: yes/no
```
So we just go with this?
