### ISSUE TITLE
Ansible: Rework port variables.

### ISSUE THREAD

**Issue by saltydk** [saltyorg/Saltbox#46]
Currently doesn't make a whole lot of sense

``` yaml
sonarr_docker_ports_defaults:
  - "{{ sonarr_web_port }}"
sonarr_docker_ports_custom: []
sonarr_docker_ports: "{{ sonarr_docker_ports_defaults
                         + sonarr_docker_ports_custom
                      if (not reverse_proxy_is_enabled)
                      else [] + sonarr_docker_ports_custom }}"
```
Where defaults is only active if running without reverse proxy and you need to add another variable to add "default" port bindings. Should make a webui specific port label so that defaults will contain the ports that need to be used in addition to the webui port.
